camel:
  springboot:
    main-run-controller: true
kafka:
  broker1:
    host: 'localhost:9092'
    camel-request-path: kafka:requests?brokers={{kafka.broker1.host}}&groupId=camel
  broker2:
    host: 'localhost:19092'
spring:
  datasource:
    url: jdbc:postgresql://localhost/shooter
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver